export const TEACHING_INPUT_SUCCESS = 'TEACHING_INPUT_SUCCESS'; 
export const TEACHING_GET_SUCCESS = 'TEACHING_GET_SUCCESS'; 
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'; 
export const UPDATE_COURSE = 'UPDATE_COURSE';