export const TODO_INPUT_SUCCESS = 'TODO_INPUT_SUCCESS';
export const TODO_GET_SUCCESS = 'TODO_GET_SUCCESS'; 
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'; 
export const UPDATE_TODO = 'UPDATE_TODO';